general_settings:
  master_key: sk-litellm-master-key
  port: 4000
  host: 0.0.0.0
  store_model_in_db: false
model_list:
- model_name: C4AI-Command-R-Plus
  litellm_params:
    model: openai/LLM-Research/c4ai-command-r-plus-08-2024
    api_key: ms-919b1188-52f3-4654-b3bd-c46ab3bcf738
    timeout: 60
    api_base: https://api-inference.modelscope.cn/v1/
