agents:
  - name: default
    display_name: 通用软件工程助手
    description: 处理通用软件工程任务
    system_prompt_sections:
      - introduction
      - system
      - doing_tasks
      - using_tools
      - tone
      - output_efficiency
      - task_management
      - asking_questions
      - response_language
      - code_reference
      - mcp
    tools:
      - Skill
      - Glob
      - LS
      - Grep
      - Read
      - RunCommand
      - CheckCommandStatus
      - StopCommand
      - run_mcp
      - TodoWrite
      - SearchReplace
      - Write
      - DeleteFile
      - AskUserQuestion
    mcp_servers:
      - mcp_seekdb
      # - mcp_Chrome_DevTools_MCP
      - mcp_rule_engine
    skills: []
    model: moonshotai/Kimi-K2.5
    #model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    #model: Qwen/Qwen3-8B
    api_key: sk-litellm-master-key
    base_url: http://localhost:4000
    temperature: 0.7
    max_iterations: 10
    max_history: 20
    enable_streaming: true
    message_builder_options:
      enable_skill_reminder: true
      enable_language_settings: true

  - name: autofill
    display_name: 自动填单助手
    description: 专门处理服务记录表单自动填写
    system_prompt_sections:
      - introduction
      - system
      - doing_tasks
      - using_tools
      - tone
      - output_efficiency
      - task_management
      - asking_questions
      - response_language
      - autofill_instruction
    tools:
      - Skill
      - RunCommand
      - TodoWrite
      - AskUserQuestion
    skills:
      - autofill-form
    #model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    model: Qwen/Qwen3-8B
    api_key: sk-litellm-master-key
    base_url: http://localhost:4000
    temperature: 0.7
    max_iterations: 20
    max_history: 20
    enable_streaming: true
    message_builder_options:
      enable_skill_reminder: true
      enable_language_settings: true
