from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `api` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `api_code` VARCHAR(100) NOT NULL UNIQUE COMMENT 'API唯一编码',
    `path` VARCHAR(100) NOT NULL  COMMENT 'API路径',
    `method` VARCHAR(6) NOT NULL  COMMENT '请求方法',
    `summary` VARCHAR(500) NOT NULL  COMMENT '请求简介' DEFAULT '',
    `tags` VARCHAR(100) NOT NULL  COMMENT 'API标签' DEFAULT '',
    KEY `idx_api_created_78d19f` (`created_at`),
    KEY `idx_api_updated_643c8b` (`updated_at`),
    KEY `idx_api_api_cod_691820` (`api_code`),
    KEY `idx_api_path_9ed611` (`path`),
    KEY `idx_api_method_a46dfb` (`method`),
    KEY `idx_api_summary_400f73` (`summary`),
    KEY `idx_api_tags_04ae27` (`tags`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `app_management` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称(英文)' DEFAULT '',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `api_key` VARCHAR(64) NOT NULL UNIQUE COMMENT 'API密钥',
    `dify_url` VARCHAR(255) NOT NULL  COMMENT 'Dify服务地址' DEFAULT '',
    `dify_api_key` VARCHAR(128) NOT NULL  COMMENT 'Dify API密钥' DEFAULT '',
    `description` VARCHAR(255) NOT NULL  COMMENT '应用描述' DEFAULT '',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    KEY `idx_app_managem_created_60ea34` (`created_at`),
    KEY `idx_app_managem_updated_cefa69` (`updated_at`),
    KEY `idx_app_managem_app_nam_29b82e` (`app_name`),
    KEY `idx_app_managem_tenant__4368da` (`tenant_id`),
    KEY `idx_app_managem_is_acti_8c8fa0` (`is_active`)
) CHARACTER SET utf8mb4 COMMENT='应用管理表';
CREATE TABLE IF NOT EXISTS `auditlog` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL  COMMENT '用户ID',
    `username` VARCHAR(64) NOT NULL  COMMENT '用户名称' DEFAULT '',
    `module` VARCHAR(64) NOT NULL  COMMENT '功能模块' DEFAULT '',
    `summary` VARCHAR(128) NOT NULL  COMMENT '请求描述' DEFAULT '',
    `method` VARCHAR(10) NOT NULL  COMMENT '请求方法' DEFAULT '',
    `path` VARCHAR(255) NOT NULL  COMMENT '请求路径' DEFAULT '',
    `status` INT NOT NULL  COMMENT '状态码' DEFAULT -1,
    `response_time` INT NOT NULL  COMMENT '响应时间(单位ms)' DEFAULT 0,
    `request_args` JSON NOT NULL  COMMENT '请求参数',
    `response_body` JSON NOT NULL  COMMENT '返回数据',
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `tenant_domain` VARCHAR(255) NOT NULL  COMMENT '租户域名' DEFAULT '',
    KEY `idx_auditlog_created_cc33d0` (`created_at`),
    KEY `idx_auditlog_updated_2f871f` (`updated_at`),
    KEY `idx_auditlog_user_id_4b93fa` (`user_id`),
    KEY `idx_auditlog_usernam_b187b3` (`username`),
    KEY `idx_auditlog_module_04058b` (`module`),
    KEY `idx_auditlog_summary_3e27da` (`summary`),
    KEY `idx_auditlog_method_4270a2` (`method`),
    KEY `idx_auditlog_path_b99502` (`path`),
    KEY `idx_auditlog_status_2a72d2` (`status`),
    KEY `idx_auditlog_respons_8caa87` (`response_time`),
    KEY `idx_auditlog_tenant__fe316e` (`tenant_id`),
    KEY `idx_auditlog_tenant__a8c151` (`tenant_domain`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `dept` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '部门名称',
    `desc` VARCHAR(500) NOT NULL  COMMENT '备注' DEFAULT '',
    `is_deleted` BOOL NOT NULL  COMMENT '软删除标记' DEFAULT 0,
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父部门ID' DEFAULT 0,
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    KEY `idx_dept_created_4b11cf` (`created_at`),
    KEY `idx_dept_updated_0c0bd1` (`updated_at`),
    KEY `idx_dept_name_c2b9da` (`name`),
    KEY `idx_dept_is_dele_466228` (`is_deleted`),
    KEY `idx_dept_order_ddabe1` (`order`),
    KEY `idx_dept_parent__a71a57` (`parent_id`),
    KEY `idx_dept_tenant__85bd2c` (`tenant_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `deptclosure` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ancestor` INT NOT NULL  COMMENT '父代',
    `descendant` INT NOT NULL  COMMENT '子代',
    `level` INT NOT NULL  COMMENT '深度' DEFAULT 0,
    KEY `idx_deptclosure_created_96f6ef` (`created_at`),
    KEY `idx_deptclosure_updated_41fc08` (`updated_at`),
    KEY `idx_deptclosure_ancesto_fbc4ce` (`ancestor`),
    KEY `idx_deptclosure_descend_2ae8b1` (`descendant`),
    KEY `idx_deptclosure_level_ae16b2` (`level`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `dropdown_option` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `summary` VARCHAR(500) NOT NULL  COMMENT '显示标签（下拉框中显示的文本）' DEFAULT '',
    `description` LONGTEXT NOT NULL  COMMENT '选项说明（帮助提示信息）',
    `class_name` VARCHAR(64) NOT NULL  COMMENT '模板分类' DEFAULT '',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `parent_id` BIGINT NOT NULL  COMMENT '父选项ID，0表示顶级选项' DEFAULT 0,
    `option_value` VARCHAR(128) NOT NULL  COMMENT '选项编码（唯一标识，如 EVT001）' DEFAULT '',
    KEY `idx_dropdown_op_created_bf032d` (`created_at`),
    KEY `idx_dropdown_op_updated_998699` (`updated_at`),
    KEY `idx_dropdown_op_class_n_a56098` (`class_name`),
    KEY `idx_dropdown_op_tenant__c362f8` (`tenant_id`),
    KEY `idx_dropdown_op_app_nam_a4098e` (`app_name`),
    KEY `idx_dropdown_op_parent__31b1a3` (`parent_id`),
    KEY `idx_dropdown_op_option__ca0c87` (`option_value`)
) CHARACTER SET utf8mb4 COMMENT='下拉选项类填单模板表';
CREATE TABLE IF NOT EXISTS `field_group_config` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `group_name` VARCHAR(64) NOT NULL  COMMENT '字段组名称' DEFAULT '',
    `group_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '字段组编码',
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `prompt_template_base` LONGTEXT NOT NULL  COMMENT 'Prompt基础模板，包含{{fields_instructions}}占位符',
    `output_templates` JSON NOT NULL  COMMENT '多输出模板配置，如{key: {template, description}}',
    `description` LONGTEXT NOT NULL  COMMENT '字段组描述',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `version` INT NOT NULL  COMMENT '版本号，用于缓存控制' DEFAULT 1,
    KEY `idx_field_group_created_4cca99` (`created_at`),
    KEY `idx_field_group_updated_21d94b` (`updated_at`),
    KEY `idx_field_group_group_n_f9f261` (`group_name`),
    KEY `idx_field_group_group_c_6a2460` (`group_code`),
    KEY `idx_field_group_app_nam_a6d697` (`app_name`),
    KEY `idx_field_group_tenant__27cadd` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='字段组配置表 - 直接关联应用，不再关联页面';
CREATE TABLE IF NOT EXISTS `field_group_field_spec` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `field_group_id` BIGINT NOT NULL  COMMENT '字段组ID' DEFAULT 0,
    `field_spec_id` BIGINT NOT NULL  COMMENT '字段明细ID' DEFAULT 0,
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    KEY `idx_field_group_created_c6b2a9` (`created_at`),
    KEY `idx_field_group_updated_2ba9ec` (`updated_at`),
    KEY `idx_field_group_field_g_34aaed` (`field_group_id`),
    KEY `idx_field_group_field_s_06ab56` (`field_spec_id`),
    KEY `idx_field_group_tenant__f6cc53` (`tenant_id`),
    KEY `idx_field_group_app_nam_a2f5aa` (`app_name`)
) CHARACTER SET utf8mb4 COMMENT='字段组与字段关联中间表（多对多关系）';
CREATE TABLE IF NOT EXISTS `field_spec` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `field_name` VARCHAR(64) NOT NULL  COMMENT '字段英文名（用于JSON输出）' DEFAULT '',
    `field_label` VARCHAR(128) NOT NULL  COMMENT '字段显示名称' DEFAULT '',
    `field_type` VARCHAR(13) NOT NULL  COMMENT '字段类型' DEFAULT 'text',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `fill_instruction` LONGTEXT NOT NULL  COMMENT '字段填写指引（用于生成LLM描述）',
    `options` JSON NOT NULL  COMMENT 'select类型选项配置，含items/min_selections/max_selections',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    UNIQUE KEY `uid_field_spec_field_n_ef6037` (`field_name`, `tenant_id`, `app_name`),
    KEY `idx_field_spec_created_81c37b` (`created_at`),
    KEY `idx_field_spec_updated_47b50f` (`updated_at`),
    KEY `idx_field_spec_tenant__1af7db` (`tenant_id`),
    KEY `idx_field_spec_app_nam_81760b` (`app_name`)
) CHARACTER SET utf8mb4 COMMENT='字段明细表 - 核心表（多对多关联字段组，通过中间表显式查询）';
CREATE TABLE IF NOT EXISTS `fill_data_record` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `session_id` VARCHAR(64) NOT NULL  COMMENT '会话ID' DEFAULT '',
    `phone` VARCHAR(32) NOT NULL  COMMENT '手机号' DEFAULT '',
    `user_unique_id` VARCHAR(64) NOT NULL  COMMENT '用户唯一标识' DEFAULT '',
    `user_name` VARCHAR(64) NOT NULL  COMMENT '用户名称' DEFAULT '',
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `data` JSON NOT NULL  COMMENT '填单数据',
    `status` VARCHAR(32) NOT NULL  COMMENT '处理状态: pending/queued/processing/completed/failed/timeout' DEFAULT 'pending',
    `result` JSON NOT NULL  COMMENT 'AI填单结果数据',
    `error_msg` LONGTEXT NOT NULL  COMMENT '错误信息',
    `processed_at` DATETIME(6)   COMMENT '处理完成时间',
    KEY `idx_fill_data_r_created_fd4aad` (`created_at`),
    KEY `idx_fill_data_r_updated_7c4fd7` (`updated_at`),
    KEY `idx_fill_data_r_session_7d06e1` (`session_id`),
    KEY `idx_fill_data_r_phone_4422ae` (`phone`),
    KEY `idx_fill_data_r_user_un_ccf5ac` (`user_unique_id`),
    KEY `idx_fill_data_r_user_na_076a2d` (`user_name`),
    KEY `idx_fill_data_r_app_nam_9a13a6` (`app_name`),
    KEY `idx_fill_data_r_tenant__74ed4c` (`tenant_id`),
    KEY `idx_fill_data_r_status_486af0` (`status`)
) CHARACTER SET utf8mb4 COMMENT='填单数据记录表';
CREATE TABLE IF NOT EXISTS `llm_config` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(128) NOT NULL  COMMENT '配置名称' DEFAULT '',
    `model_provider` VARCHAR(64) NOT NULL  COMMENT '模型提供商' DEFAULT '',
    `litellm_params` JSON NOT NULL  COMMENT 'LiteLLM 参数配置',
    `model_info` JSON NOT NULL  COMMENT '模型元信息',
    `capabilities` JSON NOT NULL  COMMENT '结构化输出方法能力配置',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `is_default` BOOL NOT NULL  COMMENT '是否为默认配置' DEFAULT 0,
    `description` LONGTEXT NOT NULL  COMMENT '配置描述',
    KEY `idx_llm_config_created_942b79` (`created_at`),
    KEY `idx_llm_config_updated_1c1f7f` (`updated_at`),
    KEY `idx_llm_config_name_2543c4` (`name`),
    KEY `idx_llm_config_model_p_27e9e8` (`model_provider`),
    KEY `idx_llm_config_is_acti_13b373` (`is_active`),
    KEY `idx_llm_config_is_defa_bab47a` (`is_default`)
) CHARACTER SET utf8mb4 COMMENT='LLM 模型配置表（全局配置）';
CREATE TABLE IF NOT EXISTS `llm_provider` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `value` VARCHAR(64) NOT NULL UNIQUE COMMENT '提供商标识',
    `label` VARCHAR(128) NOT NULL  COMMENT '提供商显示名称' DEFAULT '',
    `description` LONGTEXT NOT NULL  COMMENT '提供商描述',
    `icon` VARCHAR(255) NOT NULL  COMMENT '图标URL或类名' DEFAULT '',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    KEY `idx_llm_provide_created_bf4e35` (`created_at`),
    KEY `idx_llm_provide_updated_1d4b39` (`updated_at`),
    KEY `idx_llm_provide_value_b814ed` (`value`),
    KEY `idx_llm_provide_is_acti_1d832a` (`is_active`),
    KEY `idx_llm_provide_order_4e91e9` (`order`)
) CHARACTER SET utf8mb4 COMMENT='LLM 提供商表';
CREATE TABLE IF NOT EXISTS `menu` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '菜单名称',
    `remark` JSON NOT NULL  COMMENT '保留字段',
    `menu_type` VARCHAR(7) NOT NULL  COMMENT '菜单类型' DEFAULT 'catalog',
    `icon` VARCHAR(100) NOT NULL  COMMENT '菜单图标' DEFAULT '',
    `path` VARCHAR(100) NOT NULL  COMMENT '菜单路径' DEFAULT '',
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父菜单ID' DEFAULT 0,
    `is_hidden` BOOL NOT NULL  COMMENT '是否隐藏' DEFAULT 0,
    `component` VARCHAR(100) NOT NULL  COMMENT '组件' DEFAULT '',
    `keepalive` BOOL NOT NULL  COMMENT '存活' DEFAULT 1,
    `redirect` VARCHAR(100) NOT NULL  COMMENT '重定向' DEFAULT '',
    KEY `idx_menu_created_b6922b` (`created_at`),
    KEY `idx_menu_updated_e6b0a1` (`updated_at`),
    KEY `idx_menu_name_b9b853` (`name`),
    KEY `idx_menu_path_bf95b2` (`path`),
    KEY `idx_menu_order_606068` (`order`),
    KEY `idx_menu_parent__bebd15` (`parent_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '角色名称',
    `desc` VARCHAR(500) NOT NULL  COMMENT '角色描述' DEFAULT '',
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `is_system` BOOL NOT NULL  COMMENT '是否系统角色' DEFAULT 0,
    KEY `idx_role_created_7f5f71` (`created_at`),
    KEY `idx_role_updated_5dd337` (`updated_at`),
    KEY `idx_role_name_e5618b` (`name`),
    KEY `idx_role_tenant__f60cfc` (`tenant_id`),
    KEY `idx_role_is_syst_08cb7f` (`is_system`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role_api` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `role_id` INT NOT NULL  COMMENT '角色ID',
    `api_id` INT NOT NULL  COMMENT 'API ID',
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    UNIQUE KEY `uid_role_api_role_id_ba4286` (`role_id`, `api_id`),
    KEY `idx_role_api_created_1c2695` (`created_at`),
    KEY `idx_role_api_updated_66e6a4` (`updated_at`),
    KEY `idx_role_api_role_id_e4f7a7` (`role_id`),
    KEY `idx_role_api_api_id_19c1ec` (`api_id`),
    KEY `idx_role_api_tenant__51784f` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='角色-API关联表';
CREATE TABLE IF NOT EXISTS `role_menu` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `role_id` INT NOT NULL  COMMENT '角色ID',
    `menu_id` INT NOT NULL  COMMENT '菜单ID',
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    UNIQUE KEY `uid_role_menu_role_id_90801c` (`role_id`, `menu_id`),
    KEY `idx_role_menu_created_78e483` (`created_at`),
    KEY `idx_role_menu_updated_927ed0` (`updated_at`),
    KEY `idx_role_menu_role_id_1a25fd` (`role_id`),
    KEY `idx_role_menu_menu_id_664748` (`menu_id`),
    KEY `idx_role_menu_tenant__c1ea99` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='角色-菜单关联表';
CREATE TABLE IF NOT EXISTS `rule_info` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `rule_code` VARCHAR(64) NOT NULL  COMMENT '规则唯一编码',
    `rule_name` VARCHAR(128) NOT NULL  COMMENT '规则名称',
    `desc` VARCHAR(512) NOT NULL  COMMENT '规则描述' DEFAULT '',
    `latest_version_id` BIGINT   COMMENT '最新版本ID',
    `config` LONGTEXT   COMMENT 'CSV导入配置（JSON格式）',
    `curl_config` LONGTEXT   COMMENT 'CURL导入配置（JSON格式）',
    `status` INT NOT NULL  COMMENT '状态：0-禁用，1-启用' DEFAULT 1,
    `deleted` INT NOT NULL  COMMENT '是否删除：0-未删除，1-已删除' DEFAULT 0,
    `deleted_at` DATETIME(6)   COMMENT '删除时间',
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY `uid_rule_info_tenant__cecb8d` (`tenant_id`, `app_name`, `rule_code`),
    KEY `idx_rule_info_tenant__6aea26` (`tenant_id`),
    KEY `idx_rule_info_app_nam_1d847d` (`app_name`),
    KEY `idx_rule_info_rule_co_877ba2` (`rule_code`),
    KEY `idx_rule_info_deleted_787d7e` (`deleted`),
    KEY `idx_rule_info_created_53eea6` (`created_at`)
) CHARACTER SET utf8mb4 COMMENT='规则信息表';
CREATE TABLE IF NOT EXISTS `rule_version` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `rule_id` BIGINT NOT NULL  COMMENT '规则ID',
    `rule_code` VARCHAR(64) NOT NULL  COMMENT '规则编码' DEFAULT '',
    `version_no` INT NOT NULL  COMMENT '版本号，从1开始递增',
    `content_md5` VARCHAR(32) NOT NULL  COMMENT '内容MD5，用于乐观锁',
    `seekdb_collection_name` VARCHAR(128) NOT NULL  COMMENT 'seekdb 集合名称' DEFAULT '',
    `doc_count` BIGINT NOT NULL  COMMENT 'CSV 数据行数' DEFAULT 0,
    `headers` JSON   COMMENT 'CSV 表头列表（JSON格式）',
    `remark` VARCHAR(512) NOT NULL  COMMENT '版本备注，记录本次修改内容' DEFAULT '',
    `status` INT NOT NULL  COMMENT '状态：0-废弃，1-有效' DEFAULT 1,
    `deleted` INT NOT NULL  COMMENT '是否删除：0-未删除，1-已删除' DEFAULT 0,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    KEY `idx_rule_versio_tenant__2833b9` (`tenant_id`),
    KEY `idx_rule_versio_app_nam_ced28f` (`app_name`),
    KEY `idx_rule_versio_rule_id_7b9e47` (`rule_id`),
    KEY `idx_rule_versio_deleted_82f38f` (`deleted`),
    KEY `idx_rule_versio_created_6d20fe` (`created_at`)
) CHARACTER SET utf8mb4 COMMENT='规则版本表 - 使用 seekdb 存储 CSV 数据';
CREATE TABLE IF NOT EXISTS `summary_template` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(128) NOT NULL  COMMENT '模板名称' DEFAULT '',
    `app_name` VARCHAR(64) NOT NULL  COMMENT '应用名称' DEFAULT '',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `class_name` VARCHAR(64) NOT NULL  COMMENT '模板分类' DEFAULT '',
    `summary` VARCHAR(500) NOT NULL  COMMENT '模板摘要' DEFAULT '',
    `template_content` LONGTEXT NOT NULL  COMMENT '模板内容',
    KEY `idx_summary_tem_created_72fd74` (`created_at`),
    KEY `idx_summary_tem_updated_e49853` (`updated_at`),
    KEY `idx_summary_tem_name_f14844` (`name`),
    KEY `idx_summary_tem_app_nam_a5c5e5` (`app_name`),
    KEY `idx_summary_tem_tenant__afb478` (`tenant_id`),
    KEY `idx_summary_tem_class_n_7f4a28` (`class_name`)
) CHARACTER SET utf8mb4 COMMENT='总结类填单模板表';
CREATE TABLE IF NOT EXISTS `system_prompt` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(128) NOT NULL  COMMENT '提示词名称',
    `tenant_id` BIGINT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    `content` LONGTEXT NOT NULL  COMMENT '提示词内容',
    `description` LONGTEXT NOT NULL  COMMENT '提示词描述',
    `is_default` BOOL NOT NULL  COMMENT '是否为默认提示词' DEFAULT 0,
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `category` VARCHAR(64) NOT NULL  COMMENT '分类: general/choice/text/multi_task' DEFAULT 'general',
    UNIQUE KEY `uid_system_prom_name_ad3402` (`name`, `tenant_id`),
    KEY `idx_system_prom_created_7a96f8` (`created_at`),
    KEY `idx_system_prom_updated_65f601` (`updated_at`),
    KEY `idx_system_prom_name_62c7a6` (`name`),
    KEY `idx_system_prom_tenant__c17079` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='系统提示词表';
CREATE TABLE IF NOT EXISTS `tenant` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(50) NOT NULL  COMMENT '租户名称',
    `domain` VARCHAR(100) NOT NULL UNIQUE COMMENT '租户域名',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `description` VARCHAR(500) NOT NULL  COMMENT '租户描述' DEFAULT '',
    KEY `idx_tenant_created_69e527` (`created_at`),
    KEY `idx_tenant_updated_33376c` (`updated_at`),
    KEY `idx_tenant_name_71239f` (`name`),
    KEY `idx_tenant_domain_9ee547` (`domain`),
    KEY `idx_tenant_is_acti_b35cfb` (`is_active`)
) CHARACTER SET utf8mb4 COMMENT='租户模型';
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `username` VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名称',
    `alias` VARCHAR(30) NOT NULL  COMMENT '姓名' DEFAULT '',
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '邮箱',
    `phone` VARCHAR(20) NOT NULL  COMMENT '电话' DEFAULT '',
    `password` VARCHAR(128) NOT NULL  COMMENT '密码' DEFAULT '',
    `avatar` VARCHAR(500) NOT NULL  COMMENT '头像URL' DEFAULT '',
    `is_active` BOOL NOT NULL  COMMENT '是否激活' DEFAULT 1,
    `is_superuser` BOOL NOT NULL  COMMENT '是否为超级管理员' DEFAULT 0,
    `last_login` DATETIME(6)   COMMENT '最后登录时间',
    `dept_id` INT NOT NULL  COMMENT '部门ID' DEFAULT 0,
    `current_tenant_id` INT NOT NULL  COMMENT '当前租户ID' DEFAULT 0,
    KEY `idx_user_created_b19d59` (`created_at`),
    KEY `idx_user_updated_dfdb43` (`updated_at`),
    KEY `idx_user_usernam_9987ab` (`username`),
    KEY `idx_user_alias_6f9868` (`alias`),
    KEY `idx_user_email_1b4f1c` (`email`),
    KEY `idx_user_phone_4e3ecc` (`phone`),
    KEY `idx_user_avatar_fdfabe` (`avatar`),
    KEY `idx_user_is_acti_83722a` (`is_active`),
    KEY `idx_user_is_supe_b8a218` (`is_superuser`),
    KEY `idx_user_last_lo_af118a` (`last_login`),
    KEY `idx_user_dept_id_d4490b` (`dept_id`),
    KEY `idx_user_current_275ce6` (`current_tenant_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user_role` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL  COMMENT '用户ID',
    `role_id` INT NOT NULL  COMMENT '角色ID',
    `tenant_id` INT NOT NULL  COMMENT '租户ID' DEFAULT 0,
    UNIQUE KEY `uid_user_role_user_id_d0bad3` (`user_id`, `role_id`),
    KEY `idx_user_role_created_562302` (`created_at`),
    KEY `idx_user_role_updated_32c2e4` (`updated_at`),
    KEY `idx_user_role_user_id_f6aae2` (`user_id`),
    KEY `idx_user_role_role_id_fea46d` (`role_id`),
    KEY `idx_user_role_tenant__ed43a9` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='用户-角色关联表';
CREATE TABLE IF NOT EXISTS `user_tenant` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL  COMMENT '用户ID',
    `tenant_id` INT NOT NULL  COMMENT '租户ID',
    UNIQUE KEY `uid_user_tenant_user_id_5062c6` (`user_id`, `tenant_id`),
    KEY `idx_user_tenant_created_1b984c` (`created_at`),
    KEY `idx_user_tenant_updated_adf795` (`updated_at`),
    KEY `idx_user_tenant_user_id_cd0eaf` (`user_id`),
    KEY `idx_user_tenant_tenant__a90289` (`tenant_id`)
) CHARACTER SET utf8mb4 COMMENT='用户-租户关联表';
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
